INSERT INTO DEPARTMENT (DEPARTMENT_ID,DEPARTMENT_NAME,DEPARTMENT_ADDRESS,DEPARTMENT_CODE)
VALUES (1,'IT Department', 'A1-TOWER','IT-001');

INSERT INTO DEPARTMENT (DEPARTMENT_ID,DEPARTMENT_NAME,DEPARTMENT_ADDRESS,DEPARTMENT_CODE)
VALUES (2,'EC Department', 'A2-TOWER','EC-001');
