INSERT INTO EXPENSE (EXPENSE_ID,EXPENSE_NAME,EXPENSE_DESCRIPTION,EXPENSE_AMOUNT)
VALUES (1,'Internet', 'Internet Bill',700);

INSERT INTO EXPENSE (EXPENSE_ID,EXPENSE_NAME,EXPENSE_DESCRIPTION,EXPENSE_AMOUNT)
VALUES (2,'Electricity', 'Electricity Bill',1000);

INSERT INTO EXPENSE (EXPENSE_ID,EXPENSE_NAME,EXPENSE_DESCRIPTION,EXPENSE_AMOUNT)
VALUES (3,'Rent', 'House Rent',15000);

INSERT INTO EXPENSE (EXPENSE_ID,EXPENSE_NAME,EXPENSE_DESCRIPTION,EXPENSE_AMOUNT)
VALUES (4,'Gas', 'Gas Bill',500);
