INSERT INTO USER (USER_ID, USER_NAME, DATE_OF_BIRTH) VALUES(1, 'User1', '1993-03-20');
INSERT INTO USER (USER_ID, USER_NAME, DATE_OF_BIRTH) VALUES(2, 'User2', '1994-04-25');

INSERT INTO POST (POST_ID, DESCRIPTION, USER_ID) VALUES(1, 'Post1', 1);
INSERT INTO POST (POST_ID, DESCRIPTION, USER_ID) VALUES(2, 'Post2', 1);

